# Generated by Django 5.2.13 on 2026-09-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contact_person',
            field=models.CharField(blank=True, db_collation='nl-NL-x-icu', help_text='Name of the person to contact about this application and the associated credentials.', max_length=200, verbose_name='contact person'),
        ),
    ]
