openapi: 3.0.3
info:
  title: WOO Publications
  version: 0.1.0
  description: WIP
  contact:
    url: https://github.com/GeneriekPublicatiePlatformWoo/registratie-component
    email: support@maykinmedia.nl
  license:
    name: EUPL
    url: https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/blob/main/LICENSE.md
paths: {}
components: {}
externalDocs:
  description: Functional and technical documentation
  url: https://odrc.readthedocs.io/
