openapi: 3.0.3
info:
  title: WOO Publications
  version: 0.1.0
  description: WIP
  contact:
    url: https://github.com/GeneriekPublicatiePlatformWoo/registratie-component
    email: support@maykinmedia.nl
  license:
    name: EUPL
    url: https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/blob/main/LICENSE.md
paths:
  /api/v1/informatiecategorieen/:
    get:
      operationId: informatiecategorieenList
      description: Geeft een resultatenlijst (met paginering) terug van de bestaande
        informatiecategorieën.
      summary: Alle beschikbare informatiecategorieën.
      parameters:
      - in: query
        name: identifier
        schema:
          type: string
          format: uri
          title: Identificatie
        description: Zoek een informatiecategorie op basis van de unieke IRI die een
          specifieke categorie identificeert.
      - in: query
        name: naam
        schema:
          type: string
        description: Zoek informatiecategorieën op basis van de categorienaam.
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - Informatiecategorieën
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedInformationCategoryList'
          description: ''
  /api/v1/informatiecategorieen/{uuid}/:
    get:
      operationId: informatiecategorieenRetrieve
      description: Haal een specifiieke informatiecategorie op.
      summary: Haal een specifiieke informatiecategorie op.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - Informatiecategorieën
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationCategory'
          description: ''
  /api/v1/publicaties/:
    get:
      operationId: publicatiesList
      description: Geeft een lijst (met paginering) terug van alle bestaande publicaties.
      summary: Alle beschikbare publicaties.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - in: query
        name: sorteer
        schema:
          type: array
          items:
            type: string
            enum:
            - -officiele_titel
            - -registratiedatum
            - -verkorte_titel
            - officiele_titel
            - registratiedatum
            - verkorte_titel
        description: |-
          Sorteren op.

          * `registratiedatum` - Registratiedatum
          * `-registratiedatum` - Registratiedatum (aflopend)
          * `officiele_titel` - Officiele titel
          * `-officiele_titel` - Officiele titel (aflopend)
          * `verkorte_titel` - Verkorte titel
          * `-verkorte_titel` - Verkorte titel (aflopend)
        explode: false
        style: form
      tags:
      - Publicaties
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPublicationList'
          description: ''
    post:
      operationId: publicatiesCreate
      description: Maak een publicatie aan.
      summary: Maak een publicatie aan.
      tags:
      - Publicaties
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publication'
        required: true
      security:
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publication'
          description: ''
  /api/v1/publicaties/{uuid}/:
    get:
      operationId: publicatiesRetrieve
      description: Haal een specifieke publicatie op.
      summary: Haal een specifieke publicatie op.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - Publicaties
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publication'
          description: ''
    put:
      operationId: publicatiesUpdate
      description: Werk een publicatie (in zijn geheel) bij.
      summary: Werk een publicatie (in zijn geheel) bij.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - Publicaties
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publication'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publication'
          description: ''
    patch:
      operationId: publicatiesPartialUpdate
      description: Werk een publicatie (gedeeltelijk) bij.
      summary: Werk een publicatie (gedeeltelijk) bij.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - Publicaties
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPublication'
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publication'
          description: ''
    delete:
      operationId: publicatiesDestroy
      description: Vernietig een publicatie.
      summary: Vernietig een publicatie.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - Publicaties
      security:
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/themas/:
    get:
      operationId: themasList
      description: Geeft een resultatenlijst (met paginering) terug van de bestaande
        thema's.
      summary: Alle beschikbare thema's.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - Themas
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedThemeList'
          description: ''
  /api/v1/themas/{uuid}/:
    get:
      operationId: themasRetrieve
      description: Haal een specifiek thema op.
      summary: Haal een specifiek thema op.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - Themas
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theme'
          description: ''
  /catalogi/api/v1/informatieobjecttypen/{uuid}:
    get:
      operationId: catalogiApiV1InformatieobjecttypenRetrieve
      description: Expose an information category as a Catalogi API `informatieobjecttype`.
      summary: Haal een documenttype op
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - Catalogi API
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogiAPIDocumentType'
          description: ''
components:
  schemas:
    CatalogiAPIDocumentType:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        catalogus:
          type: string
          format: uri
          description: URL-referentie naar de CATALOGUS waartoe dit INFORMATIEOBJECTTYPE
            behoort.
        beginGeldigheid:
          type: string
          format: date
          description: De datum waarop het is ontstaan.
        informatieobjectcategorie:
          type: string
          description: Typering van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE.
          maxLength: 80
        omschrijving:
          type: string
          description: Omschrijving van de aard van informatieobjecten van dit INFORMATIEOBJECTTYPE.
          maxLength: 80
        vertrouwelijkheidaanduiding:
          allOf:
          - $ref: '#/components/schemas/VertrouwelijkheidaanduidingEnum'
          description: |-
            Aanduiding van de mate waarin informatieobjecten van dit INFORMATIEOBJECTTYPE voor de openbaarheid bestemd zijn.

            * `openbaar` - Openbaar
            * `beperkt_openbaar` - Beperkt openbaar
            * `intern` - Intern
            * `zaakvertrouwelijk` - Zaakvertrouwelijk
            * `vertrouwelijk` - Vertrouwelijk
            * `confidentieel` - Confidentieel
            * `geheim` - Geheim
            * `zeer_geheim` - Zeer geheim
        concept:
          type: boolean
          readOnly: true
          description: Geeft aan of het object een concept betreft. Concepten zijn
            niet-definitieve versies en zouden niet gebruikt moeten worden buiten
            deze API.
        besluittypen:
          type: array
          items:
            type: string
            format: uri
          readOnly: true
          description: URL-referenties naar de BESLUITTYPEN
        zaaktypen:
          type: array
          items:
            type: string
            format: uri
          readOnly: true
          description: URL-referenties naar de ZAAKTYPEN
      required:
      - beginGeldigheid
      - besluittypen
      - catalogus
      - concept
      - informatieobjectcategorie
      - omschrijving
      - url
      - vertrouwelijkheidaanduiding
      - zaaktypen
    InformationCategory:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        identifier:
          type: string
          format: uri
          readOnly: true
          title: Identificatie
          description: De unieke IRI waarmee deze categorie gedefinieerd is in de
            overheid.nl waardelijst. Voor zelf-toegevoegde items wordt een identificatie
            gegenereerd.
        naam:
          type: string
          maxLength: 80
        naamMeervoud:
          type: string
          maxLength: 80
        definitie:
          type: string
        oorsprong:
          allOf:
          - $ref: '#/components/schemas/OorsprongEnum'
          description: |-
            Geeft aan waar de categorie gedefinieerd is, waar de gegevens opgehaald worden en hoe de identificatie dient geïnterpreteerd te worden. Als een waardelijst als oorsprong gebruikt wordt, dan kan de categorie niet bewerkt of verwijderd worden.

            * `waardelijst` - Waardelijst
            * `zelf_toegevoegd` - Zelf-toegevoegd item
        order:
          type: integer
          readOnly: true
          description: Heeft invloed op de (standaard-)sortering van categorieën in
            de resultaten.
      required:
      - identifier
      - naam
      - order
    OorsprongEnum:
      enum:
      - waardelijst
      - zelf_toegevoegd
      type: string
      description: |-
        * `waardelijst` - Waardelijst
        * `zelf_toegevoegd` - Zelf-toegevoegd item
    PaginatedInformationCategoryList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/InformationCategory'
    PaginatedPublicationList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Publication'
    PaginatedThemeList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Theme'
    PatchedPublication:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        officieleTitel:
          type: string
          title: Officiële titel
          maxLength: 255
        verkorteTitel:
          type: string
          maxLength: 255
        omschrijving:
          type: string
        registratiedatum:
          type: string
          format: date-time
          readOnly: true
          title: Geregistreerd op
          description: Systeemdatum en -tijd wanneer de publicatie in de databank
            opgeslagen is. Niet te verwarren met de creatiedatum van de publicatie,
            die typisch *voor* de registratiedatum valt.
    Publication:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        officieleTitel:
          type: string
          title: Officiële titel
          maxLength: 255
        verkorteTitel:
          type: string
          maxLength: 255
        omschrijving:
          type: string
        registratiedatum:
          type: string
          format: date-time
          readOnly: true
          title: Geregistreerd op
          description: Systeemdatum en -tijd wanneer de publicatie in de databank
            opgeslagen is. Niet te verwarren met de creatiedatum van de publicatie,
            die typisch *voor* de registratiedatum valt.
      required:
      - officieleTitel
      - registratiedatum
      - uuid
    Theme:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        identifier:
          type: string
          format: uri
          readOnly: true
          title: Identificatie
          description: De unieke IRI waarmee het thema in de overheid.nl waardenlijst
            gedefinieerd is. Voor zelf-toegevoegde items wordt een identificatie gegenereerd.
        naam:
          type: string
          maxLength: 80
        subThemes:
          type: array
          items:
            $ref: '#/components/schemas/Theme'
          description: The nested themes attached to this current theme.
        depth:
          type: integer
          maximum: 2147483647
          minimum: 0
          description: Indicates how deeply the theme is nested within its parents.
            A value of one means it's a root node, a value of 2 is a child, a value
            of three is a grandchild etc.
      required:
      - depth
      - identifier
      - naam
      - subThemes
    VertrouwelijkheidaanduidingEnum:
      enum:
      - openbaar
      - beperkt_openbaar
      - intern
      - zaakvertrouwelijk
      - vertrouwelijk
      - confidentieel
      - geheim
      - zeer_geheim
      type: string
      description: |-
        * `openbaar` - Openbaar
        * `beperkt_openbaar` - Beperkt openbaar
        * `intern` - Intern
        * `zaakvertrouwelijk` - Zaakvertrouwelijk
        * `vertrouwelijk` - Vertrouwelijk
        * `confidentieel` - Confidentieel
        * `geheim` - Geheim
        * `zeer_geheim` - Zeer geheim
externalDocs:
  description: Functional and technical documentation
  url: https://odrc.readthedocs.io/
