# Generated by Django 5.2.1 on 2025-06-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0009_alter_informationcategory_archiefnominatie"),
        ("publications", "0022_alter_document_publicatiestatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="publisher",
            field=models.ForeignKey(
                help_text="The organisation which publishes the publication.",
                limit_choices_to={"is_actief": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_publications",
                to="metadata.organisation",
                verbose_name="publisher",
            ),
        ),
    ]
