# Generated by Django 5.2.3 on 2025-07-02 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0027_document_source_url"),
        ("publications", "0028_merge_20250626_0914"),
    ]

    operations = []
