# Generated by Django 5.2.10 on 2026-01-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0033_publication_eigenaar_groep"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="metadata_gestript_op",
            field=models.DateTimeField(
                editable=False,
                help_text="System timestamp reflecting when the document was stripped.",
                null=True,
                verbose_name="metadata stripped on",
            ),
        ),
    ]
