# Generated by Django 5.2.13 on 2026-09-08 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0034_document_metadata_gestript_op"),
    ]

    operations = [
        migrations.CreateModel(
            name="InzageProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "url_bekendmaking",
                    models.URLField(
                        blank=True,
                        help_text="The online location where the announcement is published, for example on 'officielebekendmakingen.nl'.",
                        max_length=1000,
                        verbose_name="announcement URL",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        help_text="The description of the announcement.",
                        verbose_name="description",
                    ),
                ),
                (
                    "beschikbaar_rechtsmiddel",
                    models.CharField(
                        choices=[
                            ("zienswijze", "Perspective"),
                            ("bezwaar", "Objection"),
                        ],
                        help_text="The legal remedy that a citizen can employ to oppose the (predisposed) decision.",
                        max_length=20,
                        verbose_name="available legal remedy",
                    ),
                ),
                (
                    "url_reactieformulier",
                    models.URLField(
                        blank=True,
                        help_text="The URL to the web form where citizens can submit the legal remedy.",
                        max_length=1000,
                        verbose_name="announcement URL",
                    ),
                ),
                (
                    "datum_begin_inzagetermijn",
                    models.DateField(
                        help_text="The date when the inspection period starts.",
                        verbose_name="in effect from",
                    ),
                ),
                (
                    "datum_einde_inzagetermijn",
                    models.DateField(
                        help_text="The date when the inspection period comes to an end.If the end date falls on a saturday, sunday or holiday we automatically push the date back to the first available workday.",
                        verbose_name="in effect until",
                    ),
                ),
                (
                    "automatisch_intrekken",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, ensure that the publication gets redacted on the configured end date.",
                        verbose_name="automatically redact",
                    ),
                ),
                (
                    "publicatie",
                    models.OneToOneField(
                        help_text="The publication that this access procedure belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publications.publication",
                        verbose_name="publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "access procedure",
                "verbose_name_plural": "access procedures",
            },
        ),
    ]
