# Generated by Django 5.2.13 on 2026-09-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_organisationunit_uuid_and_more"),
        ("metadata", "0012_alter_organisation_oorsprong"),
        ("publications", "0035_inzageprocedure"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inzageprocedure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "datum_einde_inzagetermijn__gte",
                        models.F("datum_begin_inzagetermijn"),
                    )
                ),
                name="datum_einde_inzagetermijn_cannot_be_before_datum_einde_inzagetermijn",
                violation_error_message="The start date ({start_date}) has to happen before (or be the same as) end date (datum_einde_inzagetermijn).",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("datum_einde_geldigheid__gte", models.F("datum_begin_geldigheid"))
                ),
                name="datum_einde_geldigheid_cannot_be_before_datum_einde_geldigheid",
                violation_error_message="The start date ({start_date}) has to happen before (or be the same as) end date (datum_einde_geldigheid).",
            ),
        ),
    ]
