# Generated by Django 5.2.13 on 2026-09-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "publications",
            "0036_inzageprocedure_datum_einde_inzagetermijn_cannot_be_before_datum_einde_inzagetermijn_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inzageprocedure",
            name="url_reactieformulier",
            field=models.URLField(
                blank=True,
                help_text="The URL to the web form where citizens can submit the legal remedy. This field gets populated based on the 'available legal remedy' field and the global config when left empty.",
                max_length=1000,
                verbose_name="announcement URL",
            ),
        ),
    ]
