# Generated by Django 5.2.13 on 2026-09-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "publications",
            "0036_inzageprocedure_datum_einde_inzagetermijn_cannot_be_before_datum_einde_inzagetermijn_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="eigenaar",
        ),
    ]
