# Generated by Django 5.2.13 on 2026-09-18 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "publications",
            "0037_alter_inzageprocedure_url_reactieformulier",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="eigenaar",
        ),
    ]
