# Generated by Django 5.2.13 on 2026-09-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0037_alter_inzageprocedure_url_reactieformulier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inzageprocedure",
            name="automatisch_intrekken",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, ensure that the publication gets redacted on the configured end date.",
                verbose_name="automatically withdraw",
            ),
        ),
        migrations.AlterField(
            model_name="inzageprocedure",
            name="beschikbaar_rechtsmiddel",
            field=models.CharField(
                choices=[("zienswijze", "Perspective"), ("bezwaar", "Objection")],
                help_text="The legal procedure that a citizen can employ to oppose the (predisposed) decision.",
                max_length=20,
                verbose_name="available legal procedure",
            ),
        ),
        migrations.AlterField(
            model_name="inzageprocedure",
            name="datum_begin_inzagetermijn",
            field=models.DateField(
                help_text="The date when the inspection period starts.",
                verbose_name="inzagetermijn in effect from",
            ),
        ),
        migrations.AlterField(
            model_name="inzageprocedure",
            name="datum_einde_inzagetermijn",
            field=models.DateField(
                help_text="The date when the inspection period comes to an end.If the end date falls on a saturday, sunday or holiday we automatically push the date back to the first available workday.",
                verbose_name="inzagetermijn in effect until",
            ),
        ),
        migrations.AlterField(
            model_name="inzageprocedure",
            name="url_reactieformulier",
            field=models.URLField(
                blank=True,
                help_text="The URL to the web form where citizens can submit the legal procedure. This field gets populated based on the 'available legal procedure' field and the global config when left empty.",
                max_length=1000,
                verbose_name="legal notice URL",
            ),
        ),
    ]
