# Generated by Django 5.2.13 on 2026-09-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0038_alter_inzageprocedure_automatisch_intrekken_and_more"),
        ("publications", "0038_remove_document_eigenaar"),
    ]

    operations = []
