# Generated by Django 5.2.13 on 2026-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0038_remove_document_eigenaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='officiele_titel',
            field=models.CharField(db_collation='nl-NL-x-icu', max_length=255, verbose_name='official title'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='verkorte_titel',
            field=models.CharField(blank=True, db_collation='nl-NL-x-icu', max_length=255, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='officiele_titel',
            field=models.CharField(db_collation='nl-NL-x-icu', max_length=255, verbose_name='official title'),
        ),
    ]
