# Generated by Django 5.2.13 on 2026-09-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0039_alter_publication_officiele_titel_and_more'),
        ('publications', '0039_merge_20260925_1117'),
    ]

    operations = [
    ]
