# Generated by Django 5.2.13 on 2026-09-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "config",
            "0004_globalconfiguration_gpp_burgerportaal_publication_url_template",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="document_meta_data_stripping",
            field=models.BooleanField(
                default=True,
                help_text="Enable the meta data stripping functionality of documents.",
                verbose_name="Strip document metadata",
            ),
        ),
    ]
