# Generated by Django 5.2.13 on 2026-09-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_globalconfiguration_document_meta_data_stripping"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="objection_reaction_form_url",
            field=models.URLField(
                default="",
                help_text="The URL to the default objection reaction form.",
                max_length=500,
                verbose_name="objection reaction form URL",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="perspective_reaction_form_url",
            field=models.URLField(
                default="",
                help_text="The URL to the default perspective reaction form.",
                max_length=500,
                verbose_name="perspective reaction form URL",
            ),
            preserve_default=False,
        ),
    ]
