# Generated by Django 5.2.13 on 2026-10-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_globalconfiguration_objection_reaction_form_url_and_more"),
        (
            "zgw_consumers",
            "0027_service_oauth2_scope_service_oauth2_token_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="catalogi_api_service",
            field=models.ForeignKey(
                help_text="The service to use for informatieobjecttype objects.",
                limit_choices_to={"api_type": "ztc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="catalogi API service",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="catalogus_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the catalogus object. This field will be automatically generated if no data is provided, this means to generate it again when switching services you have to empty the field yourself. Disclaimer: A catalogus should be unique (per service) based on the RSIN, if you switch back and forth between services our application won't be able to generate the catalogus url. If you want to switch back you should provide the url manually.",
                verbose_name="catalogus url",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="default_iot_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the default informatieobjecttype object. This field will be automatically generated if no data is provided, this means to generate it again when switching services you have to empty the field yourself.",
                verbose_name="default informatieobjecttype url",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="document_meta_data_stripping",
            field=models.BooleanField(
                default=True,
                help_text="Enable the meta data stripping functionality of documents.",
                verbose_name="strip document metadata",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="documents_api_service",
            field=models.ForeignKey(
                help_text="The service to use for new document uploads - the metadata and binary content will be sent to this API.",
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="documents API service",
            ),
        ),
        migrations.AddConstraint(
            model_name="globalconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("catalogus_url__gt", ""), ("default_iot_url", ""), _connector="OR"
                ),
                name="catalogi_api_reference",
                violation_error_message="The default IOT URL field cannot be set if the Catalogi URL field is empty.",
            ),
        ),
    ]
