# Generated by Django 4.2.19 on 2025-03-28 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0007_alter_organisation_is_actief"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationcategory",
            name="archiefnominatie",
            field=models.CharField(
                choices=[("blijvend_bewaren", "Retain"), ("vernietigen", "Destroy")],
                help_text="Determines if the archived data will be retained or destroyed.",
                max_length=16,
                null=True,
                verbose_name="archive nomination",
            ),
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="bewaartermijn",
            field=models.PositiveIntegerField(
                help_text="The retention period in years.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="retention period",
            ),
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="bron_bewaartermijn",
            field=models.CharField(
                help_text="The source of the retention (example: Selectielijst gemeenten 2020).",
                max_length=255,
                null=True,
                verbose_name="retention source",
            ),
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="selectiecategorie",
            field=models.CharField(
                blank=True,
                help_text="The category within the source of the retention (example: 20.1.2).",
                max_length=255,
                verbose_name="selection category",
            ),
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="toelichting_bewaartermijn",
            field=models.TextField(blank=True, verbose_name="retention explanation"),
        ),
    ]
