# Generated by Django 5.2.11 on 2026-02-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0011_organisation_rsin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="oorsprong",
            field=models.CharField(
                choices=[
                    ("gemeentelijst", "Municipality list"),
                    ("solijst", "Collaborative organisations list"),
                    ("oorglijst", "Alternative government organisations"),
                    ("caribischelijst", "Caribbean organisations"),
                    ("provincielijst", "Province list"),
                    ("waterschaplijst", "Water Board list"),
                    ("zbolijst", "ZBO list"),
                    ("zelf_toegevoegd", "Custom entry"),
                ],
                default="zelf_toegevoegd",
                help_text="Determines where the organisation is defined and sourced from, and how the identifier should be interpreted. If the value list is the origin, the organisation can not be modified or deleted.",
                max_length=15,
                verbose_name="origin",
            ),
        ),
    ]
