# Generated by Django 5.2.13 on 2026-09-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0012_alter_organisation_oorsprong"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationcategory",
            name="iot_url",
            field=models.URLField(
                default="",
                editable=False,
                help_text="The informatieobjecttype URL from the catalogi API.",
                verbose_name="informatieobjecttype URL",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="informationcategory",
            name="iot_uuid",
            field=models.UUIDField(
                editable=False,
                help_text="The UUID of the API resource recorded in the Catalogi API.",
                null=True,
                verbose_name="informatieobjecttype UUID",
            ),
        ),
    ]
