# Generated by Django 5.2.13 on 2026-10-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0013_informationcategory_iot_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationcategory",
            name="iot_url",
            field=models.URLField(
                blank=True,
                help_text="The informatieobjecttype URL from the catalogi API.",
                verbose_name="informatieobjecttype URL",
            ),
        ),
        migrations.AlterField(
            model_name="informationcategory",
            name="iot_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="The UUID of the API resource recorded in the Catalogi API.",
                null=True,
                verbose_name="informatieobjecttype UUID",
            ),
        ),
        migrations.AddConstraint(
            model_name="informationcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("iot_url", ""), ("iot_uuid__isnull", True)),
                    models.Q(("iot_url__gt", ""), ("iot_uuid__isnull", False)),
                    _connector="OR",
                ),
                name="iot_reference",
                violation_error_message="You must specify both the IOT URL and IOT UUID to identify a Information Object Type.",
            ),
        ),
    ]
