name: generate-sdks

on:
  push:
    paths:
      - "src/odrc/api/v*/openapi.yaml"
      - ".github/workflows/generate-sdks.yml"
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 'v1' ]

    name: Run with version $

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install -g @openapitools/openapi-generator-cli
      - name: Determing oas path
        id: vars
        run: echo ::set-output name=oas::./src/odrc/api/$/openapi.yaml
      - name: Validate schema
        run: openapi-generator-cli validate -i $
      - name: Generate Java client
        run: openapi-generator-cli generate -i $ --global-property=modelTests=false,apiTests=false,modelDocs=false,apiDocs=false \
          -o ./sdks/java -g java --additional-properties=dateLibrary=java8,java8=true,optionalProjectFile=false,optionalAssemblyInfo=false
      - name: Generate .NET client
        run: openapi-generator-cli generate -i $ --global-property=modelTests=false,apiTests=false,modelDocs=false,apiDocs=false \
          -o ./sdks/net -g csharp --additional-properties=optionalProjectFile=false,optionalAssemblyInfo=false
      - name: Generate Python client
        run: openapi-generator-cli generate -i $ --global-property=modelTests=false,apiTests=false,modelDocs=false,apiDocs=false \
          -o ./sdks/python -g python --additional-properties=optionalProjectFile=false,optionalAssemblyInfo=false+
