# Run quality control on the (generated) Open API specification.

name: OpenAPI specification checks

on:
  push:
    branches:
      - main
      - stable/*
  pull_request:
  workflow_dispatch:

jobs:
  oas-shared-wf:
    uses: maykinmedia/open-api-workflows/.github/workflows/oas.yml@v5
    with:
      python-version: '3.12'
      django-settings-module: woo_publications.conf.ci
      oas-generate-command: ./bin/generate_api_schema.sh
      schema-path: src/woo_publications/api/openapi.yaml
      oas-artifact-name: gpp-publicatiebank-oas
      node-version-file: '.nvmrc'
      spectral-version: '^6.15.0'
      openapi-to-postman-version: '^5.0.0'
      postman-artifact-name: gpp-publicatiebank-postman-collection
      openapi-generator-version: '^2.20.0'
